name: 打包vue
on: push
permissions:
  contents: write
jobs:
  build:
    name: 打包
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装依赖
        run: npm install

      - name: 构建
        run: npm run build

      - name: 部署vue静态文件
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: dist